goog.require('parashutter.utils');
goog.provide('parashutter.text');

(function(window, undefined) {
    var stopWords = [
        'a',
        'a\'s',
        'able',
        'about',
        'above',
        'according',
        'accordingly',
        'across',
        'actually',
        'after',
        'afterwards',
        'again',
        'against',
        'ain\'t',
        'all',
        'allow',
        'allows',
        'almost',
        'alone',
        'along',
        'already',
        'also',
        'although',
        'always',
        'am',
        'among',
        'amongst',
        'an',
        'and',
        'another',
        'any',
        'anybody',
        'anyhow',
        'anyone',
        'anything',
        'anyway',
        'anyways',
        'anywhere',
        'apart',
        'appear',
        'appreciate',
        'appropriate',
        'are',
        'aren\'t',
        'around',
        'as',
        'aside',
        'ask',
        'asking',
        'associated',
        'at',
        'available',
        'away',
        'awfully',
        'b',
        'be',
        'became',
        'because',
        'become',
        'becomes',
        'becoming',
        'been',
        'before',
        'beforehand',
        'behind',
        'being',
        'believe',
        'below',
        'beside',
        'besides',
        'best',
        'better',
        'between',
        'beyond',
        'both',
        'brief',
        'but',
        'by',
        'c',
        'c\'mon',
        'c\'s',
        'came',
        'can',
        'can\'t',
        'cannot',
        'cant',
        'cause',
        'causes',
        'certain',
        'certainly',
        'changes',
        'clearly',
        'co',
        'com',
        'come',
        'comes',
        'concerning',
        'consequently',
        'consider',
        'considering',
        'contain',
        'containing',
        'contains',
        'corresponding',
        'could',
        'couldn\'t',
        'course',
        'currently',
        'd',
        'definitely',
        'described',
        'despite',
        'did',
        'didn\'t',
        'different',
        'do',
        'does',
        'doesn\'t',
        'doing',
        'don\'t',
        'done',
        'down',
        'downwards',
        'during',
        'e',
        'each',
        'edu',
        'eg',
        'eight',
        'either',
        'else',
        'elsewhere',
        'enough',
        'entirely',
        'especially',
        'et',
        'etc',
        'even',
        'ever',
        'every',
        'everybody',
        'everyone',
        'everything',
        'everywhere',
        'ex',
        'exactly',
        'example',
        'except',
        'f',
        'far',
        'few',
        'fifth',
        'first',
        'five',
        'followed',
        'following',
        'follows',
        'for',
        'former',
        'formerly',
        'forth',
        'four',
        'from',
        'further',
        'furthermore',
        'g',
        'get',
        'gets',
        'getting',
        'given',
        'gives',
        'go',
        'goes',
        'going',
        'gone',
        'got',
        'gotten',
        'greetings',
        'h',
        'had',
        'hadn\'t',
        'happens',
        'hardly',
        'has',
        'hasn\'t',
        'have',
        'haven\'t',
        'having',
        'he',
        'he\'s',
        'hello',
        'help',
        'hence',
        'her',
        'here',
        'here\'s',
        'hereafter',
        'hereby',
        'herein',
        'hereupon',
        'hers',
        'herself',
        'hi',
        'him',
        'himself',
        'his',
        'hither',
        'hopefully',
        'how',
        'howbeit',
        'however',
        'i',
        'i\'d',
        'i\'ll',
        'i\'m',
        'i\'ve',
        'ie',
        'if',
        'ignored',
        'immediate',
        'in',
        'inasmuch',
        'inc',
        'indeed',
        'indicate',
        'indicated',
        'indicates',
        'inner',
        'insofar',
        'instead',
        'into',
        'inward',
        'is',
        'isn\'t',
        'it',
        'it\'d',
        'it\'ll',
        'it\'s',
        'its',
        'itself',
        'j',
        'just',
        'k',
        'keep',
        'keeps',
        'kept',
        'know',
        'knows',
        'known',
        'l',
        'last',
        'lately',
        'later',
        'latter',
        'latterly',
        'least',
        'less',
        'lest',
        'let',
        'let\'s',
        'like',
        'liked',
        'likely',
        'little',
        'look',
        'looking',
        'looks',
        'ltd',
        'm',
        'mainly',
        'many',
        'may',
        'maybe',
        'me',
        'mean',
        'meanwhile',
        'merely',
        'might',
        'more',
        'moreover',
        'most',
        'mostly',
        'much',
        'must',
        'my',
        'myself',
        'n',
        'name',
        'namely',
        'nd',
        'near',
        'nearly',
        'necessary',
        'need',
        'needs',
        'neither',
        'never',
        'nevertheless',
        'new',
        'next',
        'nine',
        'no',
        'nobody',
        'non',
        'none',
        'noone',
        'nor',
        'normally',
        'not',
        'nothing',
        'novel',
        'now',
        'nowhere',
        'o',
        'obviously',
        'of',
        'off',
        'often',
        'oh',
        'ok',
        'okay',
        'old',
        'on',
        'once',
        'one',
        'ones',
        'only',
        'onto',
        'or',
        'other',
        'others',
        'otherwise',
        'ought',
        'our',
        'ours',
        'ourselves',
        'out',
        'outside',
        'over',
        'overall',
        'own',
        'p',
        'particular',
        'particularly',
        'per',
        'perhaps',
        'placed',
        'please',
        'plus',
        'possible',
        'presumably',
        'probably',
        'provides',
        'q',
        'que',
        'quite',
        'qv',
        'r',
        'rather',
        'rd',
        're',
        'really',
        'reasonably',
        'regarding',
        'regardless',
        'regards',
        'relatively',
        'respectively',
        'right',
        's',
        'said',
        'same',
        'saw',
        'say',
        'saying',
        'says',
        'second',
        'secondly',
        'see',
        'seeing',
        'seem',
        'seemed',
        'seeming',
        'seems',
        'seen',
        'self',
        'selves',
        'sensible',
        'sent',
        'serious',
        'seriously',
        'seven',
        'several',
        'shall',
        'she',
        'should',
        'shouldn\'t',
        'since',
        'six',
        'so',
        'some',
        'somebody',
        'somehow',
        'someone',
        'something',
        'sometime',
        'sometimes',
        'somewhat',
        'somewhere',
        'soon',
        'sorry',
        'specified',
        'specify',
        'specifying',
        'still',
        'sub',
        'such',
        'sup',
        'sure',
        't',
        't\'s',
        'take',
        'taken',
        'tell',
        'tends',
        'th',
        'than',
        'thank',
        'thanks',
        'thanx',
        'that',
        'that\'s',
        'thats',
        'the',
        'their',
        'theirs',
        'them',
        'themselves',
        'then',
        'thence',
        'there',
        'there\'s',
        'thereafter',
        'thereby',
        'therefore',
        'therein',
        'theres',
        'thereupon',
        'these',
        'they',
        'they\'d',
        'they\'ll',
        'they\'re',
        'they\'ve',
        'think',
        'third',
        'this',
        'thorough',
        'thoroughly',
        'those',
        'though',
        'three',
        'through',
        'throughout',
        'thru',
        'thus',
        'to',
        'together',
        'too',
        'took',
        'toward',
        'towards',
        'tried',
        'tries',
        'truly',
        'try',
        'trying',
        'twice',
        'two',
        'u',
        'un',
        'under',
        'unfortunately',
        'unless',
        'unlikely',
        'until',
        'unto',
        'up',
        'upon',
        'us',
        'use',
        'used',
        'useful',
        'uses',
        'using',
        'usually',
        'uucp',
        'v',
        'value',
        'various',
        'very',
        'via',
        'viz',
        'vs',
        'w',
        'want',
        'wants',
        'was',
        'wasn\'t',
        'way',
        'we',
        'we\'d',
        'we\'ll',
        'we\'re',
        'we\'ve',
        'welcome',
        'well',
        'went',
        'were',
        'weren\'t',
        'what',
        'what\'s',
        'whatever',
        'when',
        'whence',
        'whenever',
        'where',
        'where\'s',
        'whereafter',
        'whereas',
        'whereby',
        'wherein',
        'whereupon',
        'wherever',
        'whether',
        'which',
        'while',
        'whither',
        'who',
        'who\'s',
        'whoever',
        'whole',
        'whom',
        'whose',
        'why',
        'will',
        'willing',
        'wish',
        'with',
        'within',
        'without',
        'won\'t',
        'wonder',
        'would',
        'would',
        'wouldn\'t',
        'x',
        'y',
        'yes',
        'yet',
        'you',
        'you\'d',
        'you\'ll',
        'you\'re',
        'you\'ve',
        'your',
        'yours',
        'yourself',
        'yourselves',
        'z',
        'zero'
    ];

    function getCorpusFromElement(element) {
        var corpus = [];
        if (element.hasChildNodes()) {
            var children = element.childNodes;
            var newWords = null;
            for (var i = 0; i < children.length; i++) {
                var child = children[i];
                if (child.nodeName.toLowerCase() === 'img') {
                    var alt = child.getAttribute('alt') || '';
                    if (alt.length > 0) {
                        newWords =  alt.replace(/\W/, ' ').split(' ');
                    }
                } if (child.nodeType === 3) {
                    // text node
                    newWords = child.nodeValue.replace(
                        /\W/,
                        ' '
                    ).split(' ');
                } else if (child.nodeType === 1) {
                    // element node
                    newWords = getCorpusFromElement(child);
                }
            }

            if (newWords !== null && newWords.length > 0) {
                for (var i = 0; i < newWords.length; i++) {
                    var word = newWords[i].trim();
                    if (word === '') {
                        continue;
                    }
                    corpus.push(word);
                }
            }
        }

        return corpus;
    }

    function getCorpusFromKeywords() {
        var KEYWORD_BIAS = 10;
        var metaTags = document.getElementsByTagName('meta');
        var corpus = [];
        for (var i = 0; i < metaTags.length; i++) {
            var element = metaTags[i];
            var name = element.getAttribute('name');
            if (name === 'keywords' || name === 'description') {
                var keywordsContent = element.getAttribute('content');
                keywordsContent.replace(
                    /\W/,
                    ' '
                ).split(' ').forEach(function(keyword) {
                    if (keyword.trim() === '') {
                        return;
                    }
                    for (var i = 0; i < KEYWORD_BIAS; i++) {
                        corpus.push(keyword.trim());
                    }
                });
            }
        }

        return corpus;
    }

    function getCorpusFromDocument() {
        var corpus = getCorpusFromKeywords();
        return corpus.push.apply(
            corpus,
            getCorpusFromElement(window.document)
        );
    }

    if (!window['parashutter']) {
        window['parashutter'] = {};
    }

    window['parashutter']['getKeywords'] = function(topN, getCorpus) {
        var bagOfWords = {};
        if (!topN) {
            topN = 5;
        }
        if (!getCorpus) {
            getCorpus = getCorpusFromKeywords;
        }
        var allWords = getCorpus();
        
        allWords.forEach(function(word) {
            if (stopWords.indexOf(word) > 0) {
                return;
            }
            bagOfWords[word] = (bagOfWords[word] || 0) + 1;
        });
        sortableWords = [];

        for (var prop in bagOfWords) {
            if (bagOfWords.hasOwnProperty(prop)) {
                sortableWords.push([prop, bagOfWords[prop]]);
            }
        }

        sortableWords.sort(function(w1, w2) { return w2[1] - w1[1] });
        window.console.debug(sortableWords);
        var maxWords = Math.min(topN, sortableWords.length);

        var keywords = [];
        for (var i = 0; i < maxWords; i++) {
            keywords.push(sortableWords[i][0]);
        }

        return keywords;
    };

})(window);

